config/routes.rb
Rails.application.routes.draw do
  resources :weeks
  resources :day_logs
  devise_for :users

  root 'day_logs#index'
  get '/current', to: 'weeks#current'
  post '/current', to: 'weeks#week'

end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/day_log.rb
class DayLog < ActiveRecord::Base
	belongs_to :user
	belongs_to :week




end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :day_logs
end

app/models/week.rb
class Week < ActiveRecord::Base
	has_many :day_logs,  dependent: :destroy
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   def week_exist? 
     week = Week.where("week_strat = ?", get_sunday()).first
     
    end 

  def search(search)

     Week.where(['week_strat LIKE ?', "#{search}"])
  end

  def  get_sunday 
    date =  Date.today.beginning_of_week(:sunday)
    new_dat = date.to_s 
  end
end

app/controllers/day_logs_controller.rb
class DayLogsController < ApplicationController
  require 'active_support/core_ext/string'
  require 'date'
  before_action :set_day_log, only: [:show, :edit, :update, :destroy]

  # GET /day_logs
  # GET /day_logs.json
  def index
    @day_logs = DayLog.all
  end

  # GET /day_logs/1
  # GET /day_logs/1.json
  def show
  end

  # GET /day_logs/new
  def new
    @day_log = DayLog.new
  end

  # GET /day_logs/1/edit
  def edit
  end


def create
     if current_user 

      @day_log = set_params(params[:day], params[:time_in], params[:time_out])
      
        if week_exist? 
           week = week_exist? 
           id = week.id
           day_log = DayLog.find(@day_log.id)
           @day_log2 = day_log.update_attribute(:week_id, id) 
          
        else 
          week = get_sunday
        end 
          params = ActionController::Parameters.new({
            week: {
            week_strat: get_sunday,
            day_id:  @day_log.id,
            user_id: current_user.id
          }
        }) 
         permitted = params.require(:week).permit(:week_strat,  :day_id, :user_id)
         if  @week = Week.create!(permitted) 
             update_day_log(@week.id)
             render :show
          else
            format.html { render :new }
            format.json { render json: @week.errors, status: :unprocessable_entity }
          end

      else 
       redirect_to root_url, :notice => "You need to login befor loging your hours worked"
     end
  end

  def set_params(day, time_in, time_out)
    params = ActionController::Parameters.new({
       day_log: {
        day: day,
        time_in:  time_in,
        time_out: time_out,
        user_id: current_user.id
      }
    })
    permitted = params.require(:day_log).permit(:day, :time_in, :time_out, :user_id)

      if @day_log = DayLog.create!(permitted) 
        @day_log
      else
        format.html { render :new }
        format.json { render json: @day_log.errors, status: :unprocessable_entity }

    end
  end

  def update
    respond_to do |format|
      if @day_log.update(day_log_params)
        format.html { redirect_to @day_log, notice: 'Day log was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_log }
      else
        format.html { render :edit }
        format.json { render json: @day_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_logs/1
  # DELETE /day_logs/1.json
  def destroy
    @day_log.destroy
    respond_to do |format|
      format.html { redirect_to day_logs_url, notice: 'Day log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def update_day_log(id)

           day_log = DayLog.find(@day_log.id)
           @day_log2 = day_log.update_attribute(:week_id, id) 
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_day_log
      @day_log = DayLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_log_params
      params.require(:day_log).permit(:day, :time_in, :time_out).merge(user_id: current_user.id)
    end

    def week_exist? 
     week = Week.where("week_strat = ?", get_sunday()).first
     
    end 

  def search(search)
     Week.where(['name LIKE ?', "%#{search}%"])
  end

  def  get_sunday 
    date =  Date.today.beginning_of_week(:sunday)
    new_dat = date.to_s 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index 

 end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :edit, :update, :destroy]

  # GET /weeks
  # GET /weeks.json
  def index
    @weeks  = Week.includes(:day_logs)
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end
  def current 
    @day_logs = []
    @week = search(get_sunday)
     @week.each_with_index do |week, i|
      begin
        my_record = DayLog.find week.day_id
      rescue ActiveRecord::RecordNotFound => e
        my_record = nil
      end
      @day_logs[i] = my_record
    end 
  end
  def week  
  @day_logs = [] 
    @weeks = search(params[:find_week])

     @weeks.each_with_index do |week, i|

      begin
        my_record = DayLog.find week.day_id
      rescue ActiveRecord::RecordNotFound => e
        my_record = nil
      end
      @day_logs[i] = my_record

    end 
    binding.pry
    render :index
  end 

  # POST /weeks
  # POST /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to @week, notice: 'Week was successfully created.' }
        format.json { render :show, status: :created, location: @week }
      else
        format.html { render :new }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1
  # PATCH/PUT /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to @week, notice: 'Week was successfully updated.' }
        format.json { render :show, status: :ok, location: @week }
      else
        format.html { render :edit }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week.destroy
    respond_to do |format|
      format.html { redirect_to weeks_url, notice: 'Week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def week_params
      params.require(:week).permit(:start_day, :day_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


   



end

app/helpers/day_logs_helper.rb
module DayLogsHelper

	def  get_sunday 
		Date.today.beginning_of_week(:sunday)
	end

def week_exist? 
  if  @week = Week.search(get_sunday());
      @week;
  end
end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/day_logs/_form.html.erb
<%= form_for(@day_log) do |f| %>
  <% if @day_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_log.errors.count, "error") %> prohibited this day_log from being saved:</h2>

      <ul>
      <% @day_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :time_in %><br>
    <%= f.text_field :time_in %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br>
    <%= f.text_field :time_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/day_logs/edit.html.erb
<h1>Editing Day Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @day_log %> |
<%= link_to 'Back', day_logs_path %>

app/views/day_logs/index.html.erb
<div class="container"> 


<h1>Listing Day Logs</h1>

<table style="table-layout:fixed">
  <thead>
    <tr>
      <th>Day</th>
      <th>Time in</th>
      <th>Time out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_logs.each do |day_log| %>
      <tr>
        <td><%= day_log.day %></td>
        <td><%= day_log.time_in %></td>
        <td><%= day_log.time_out %></td>
        <td><%= day_log.week_id %></td>
        <td><%= link_to 'Show', day_log %></td>
        <td><%= link_to 'Edit', edit_day_log_path(day_log) %></td>
        <td><%= link_to 'Destroy', day_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Day log', new_day_log_path %>
</div>

app/views/day_logs/new.html.erb
<div class="container">


<%= form_for(@day_log) do |f| %>
  <% if @day_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_log.errors.count, "error") %> prohibited this day_log from being saved:</h2>

      <ul>
      <% @day_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
  
 <div class="container">
  <div class="row">
    <div class="col-md-6">
  <div class="panel ">
     <div class="panel-heading top-panel"><h4>New Day Log</h4></div>
    <div class="well">

  <div class="field">
    <%= f.label :day %><br>
    <div class="row">
        <div class='col-sm-12'>
            <div class="form-group">
                <div class='input-group date' ng-model="day"   name="day" id='datetimepicker2'>
                    <input type='text' class="form-control" id="dd" ng-model="day" onchange="myfunc()" name="day"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker2').datetimepicker({
                    locale: 'ru'
                    
                });
            });
        </script>
   

  <div class="field">
    <%= f.label :time_in %><br>
 <div class="form-group">
            <label for="tt" class="sr-only">Start Timer</label>
            <div class="input-group" id="TimeDemo">
                <input type="text" id="tt" name="time_in" placeholder="time" ng-model="user.time_in" class="form-control" />
                <span class="input-group-btn">
                    <button class="btn btn-green" type="button"><i class="glyphicon glyphicon-time	Try it
"></i></button>
                </span>
            </div>
  </div>
  
  <div class="field">
    <%= f.label :time_out %><br>

        
            <div class="form-group">
                <div class='input-group ' id='datetimepicker3'>
                    <input type="text" id="t2" name="time_out" placeholder="time" ng-model="user.time_out" class="form-control" onchange="myFunction(this.value)"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>



        <script type="text/javascript">
            $(function () {
                $('#datetimepicker3').datetimepicker({
                    format: 'LT',
                     pickDate: false,
                    minuteStepping: 5
                });
            });
        </script>

  </div>
 
  <div class="actions">
    <%= f.submit "Puch the clock", :class => "btn btn-day-log"  %>
  </div>
<% end %>


&#160;<%= link_to 'Back', day_logs_path %>
</div>
</div>
</div>
</div>
</div>
 </div>
 </div>
 </div>
   <div class="col-md-6">
    <div class="right-day-log">
      <p class="total-hours"> 6 </p>
      <h4>Total hour's for the day</h4>
    </div>
    <div class="right-week-log">
      <p class="total-hours"> 18 </p>
      <h4>Total hour's for the week</h4>
    </div>
  </div>
  </div>


 </div>

<script type="text/javascript">

 "use strict";
 (function () {
     

 

    angular.module('myApp', [])
      .controller('MyController', ['$scope', function ($scope) {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth()+1; //January is 0!
        var yyyy = today.getFullYear();

        if(dd<10) {
            dd='0'+dd
        } 

        if(mm<10) {
            mm='0'+mm
        } 

        today = mm+'/'+dd+'/'+yyyy;
        $scope.day = today;
        $scope.myFunc = function( day) {
         console.log($scope.day);
    };
      }]);

    angular.element(function() {
      angular.bootstrap(document, ['myApp']);
    });
  })();
  </script>

 

    

app/views/day_logs/show.html.erb
<div class="container"  >

<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @day_log.day %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @day_log.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @day_log.time_out %>
</p>

<%= link_to 'Edit', edit_day_log_path(@day_log) %> |
<%= link_to 'Back', day_logs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>TimeLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/images/ui-icons_444444_256x240.png"> 

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
</head>
<body  ng-controller="MyController">
	 <!-- Second navbar for sign in -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hudson Commercial work log
    			</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/day_logs/new">Home</a></li>
            <li><a href="/day_logs">New log</a></li>
            <li><a href="/weeks">Week</a></li>
            <li><a href="/tasks">Tasks</a></li>
            <li><a href="/current">Current week</a></li>
            <li>
              <a class="btn btn-default btn-outline btn-circle collapsed"  data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Sign in</a>
            </li>
          </ul>
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
              <%= form_for(resource, :html => {:class => "navbar-form navbar-right form-inline"}, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-group">
                <label class="sr-only" for="Email">Email</label>
                <%= f.email_field :email, autofocus: true, :class => "form-control" %>
              </div>
              <div class="form-group">
                <label class="sr-only" for="Password">Password</label>
                <%= f.password_field :password, autocomplete: "off", :class => "form-control"  %>
              </div>
                <%= f.submit "Log in", :class => "btn btn-success"  %>
             <% end %>
            </form>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
    
<div class="container">
  	<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>


  	<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/weeks/_form.html.erb
<%= form_for(@week) do |f| %>
  <% if @week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
      <% @week.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_day %><br>
    <%= f.text_field :start_day %>
  </div>
  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.number_field :day_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weeks/current.html.erb
 

<div class="container"> 


<h1> Work Logged For  <%= @week[0].week_strat if @week[0]%></h1>

<table style="table-layout:fixed">
  <thead>
    <tr>
      <th>Day</th>
      <th>Time in</th>
      <th>Time out</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_logs.each do |day_log| %>
       <% if day_log %>
	      <tr>
	        <td><%= day_log.day  %></td>
	        <td><%= day_log.time_in %></td>
	        <td><%= day_log.time_out %></td>
          <% time_in = day_log.time_in.gsub(':', '') %>
          <% time_in = time_in.gsub('(AM|PM)', '') %>
          <% time_in = time_in.gsub('00', '') %>
          <%= time_in %>
          <% time_out = day_log.time_out.gsub(':', '') %>
          <% time_out = time_out.gsub("(AM|PM)", '') %>
          <% time_out = time_out.gsub('00', '') %>
          <% time_in = time_in.to_i %>
          <% time_out2 = '' %>
          
          <% if time_out.size > 2 %>
          <%  time_out3 = time_out.split("").map { |s| if time_out2.length < 4 
            time_out2 += s 
            end} %>
            <%=  time_out3 %>
          <%time_out = time_out3[1] %>
          <% minutes = time_out3[3][2...4]%>
          


          <td> <%= time_in %> &nbsp; <%= time_out %>&nbsp; <%= minutes %> </td>

        
            
         
	        <td><%= link_to 'Show', day_log %></td>
	        <td><%= link_to 'Edit', edit_day_log_path(day_log) %></td>
	        <td><%= link_to 'Destroy', day_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
        <%end %>
      <% end%>
    <% end %>

  </tbody>
</table>
<br>
<br>
<%=form_tag(controller: "weeks",action: "week", method: "post") do %> 
	  <%= label_tag(:find_week, "Search for week:") %>
  	<%= text_field_tag(:find_week) %>
  	<%= submit_tag("Search") %>
  	<%end %>
<br>
<%= link_to 'New Day log', new_day_log_path %>
</div>

app/views/weeks/edit.html.erb
<h1>Editing Week</h1>

<%= render 'form' %>

<%= link_to 'Show', @week %> |
<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<div class="container">

  <h1>Listing Weeks</h1>

  <table>
    <thead>
      <tr>
        <th>Week</th>
        <th>day</th>
        <th>In</th>
        <th>Out</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @weeks.each do |week| %>
        

          <% week.day_logs.each do |day| %> 
          <tr>
            <td> <%=week.week_strat%></td>
            <td><%= day.day %></td>
            <td><%= day.time_in %></td>
            <td><%= day.time_out %></td>
          </tr>

         
            <td></td>
            <td><%= link_to 'Show', day %></td>
          <td><%= link_to 'Edit', edit_day_log_path(day) %></td>
          <td><%= link_to 'Destroy',day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <%end%>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New day', new_day_log_path %>
  <br>
  <%= link_to 'New Week', new_week_path %>
</div>

app/views/weeks/new.html.erb
<h1>New Week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start day:</strong>
  <%= @week.start_day %>
</p>

<p>
  <strong>Day:</strong>
  <%= @week.day_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @week.user_id %>
</p>

<%= link_to 'Edit', edit_week_path(@week) %> |
<%= link_to 'Back', weeks_path %>